### ISSUE TITLE
QR testing

### ISSUE THREAD

**Issue by Pankin610** [Pankin610/linalg#21]
Hi Filip, please add a QR test that would check the behaviour when the input matrix doesn't have a QR decomposition.
Or if every matrix has it please test the edge cases such as a matrix of zeros, a vector-matrix, or an identity.

**Comment by Pankin610** [comment]
Also for some reason the QR code has tab size = 4 instead of 2

**Comment by FiIipson** [comment]
I've just pushed some changes, check it out and let me know what you think
