### ISSUE TITLE
MatrixCoordinate comment

### ISSUE THREAD

**Issue by FiIipson** [Pankin610/linalg#6]
@Pankin610 I have added some small comment to `MatrixCoordinate` class. You can close that issue whenever you read it.

**Comment by Pankin610** [comment]
Can you tell where's the comment? I can't find it

**Comment by FiIipson** [comment]
[here](https://github.com/Pankin610/linalg/pull/2)

**Comment by Pankin610** [comment]
> here

Still can't see it there, maybe you forgot to upload the review

**Comment by FiIipson** [comment]
When you scroll down there is this section called "Filipson started a review"
