### ISSUE TITLE
Code does not pass any test 

### ISSUE THREAD

**Issue by FiIipson** [Pankin610/linalg#9]
Some issue @Daniil-Y to your code we have unfortunately approved yesterday
```
LUDecomposition (Matrix Mat) {
  if(Mat.Cols() != Mat.Rows()){
    throw new java.lang.IllegalArgumentException();
  }
}
  ```

That's constructor and probably some important statement misses here - sth like `this.Mat = Mat`,
thus it hasn't passed any test.

**Comment by Daniil-Y** [comment]
I fixed some bugs including this one and pushed in my branch.
